package view;
import javax.swing.Box;
import javax.swing.JOptionPane;


public class FormPrincipal extends javax.swing.JFrame {
 
    private static FormPrincipal formPrincipalUnic;
    
    private FormPrincipal() {
        initComponents();
        
    }
    
    //MÉTODO SINGLETON
    public static FormPrincipal getformPrincipalUnic(){
        
        if(formPrincipalUnic == null){
            formPrincipalUnic = new FormPrincipal();
        }
        return formPrincipalUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        mnBarPrincipal = new javax.swing.JMenuBar();
        mnCadProd = new javax.swing.JMenu();
        subMenuCadProd = new javax.swing.JMenu();
        itemSubMnAbreCadProc = new javax.swing.JMenuItem();
        itemSubMnAbreCadPlacaV = new javax.swing.JMenuItem();
        itemSubMnAbreCadPlacaM = new javax.swing.JMenuItem();
        mnRelProd = new javax.swing.JMenu();
        SubMenuRelProd = new javax.swing.JMenu();
        itemSubMnAbreRelGerProc = new javax.swing.JMenuItem();
        itemSubMnAbreRelGerPlacaV = new javax.swing.JMenuItem();
        itemSubMnAbreRelGerPlacaM = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        iMnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtTitulo.setText("Gerenciamento De Produtos");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        mnCadProd.setText("Cadastro");

        subMenuCadProd.setText("Abrir Gerenciamento Dos Produtos...");

        itemSubMnAbreCadProc.setText("Abrir Gerenciamento de Processadores...");
        itemSubMnAbreCadProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSubMnAbreCadProcActionPerformed(evt);
            }
        });
        subMenuCadProd.add(itemSubMnAbreCadProc);

        itemSubMnAbreCadPlacaV.setText("Abrir Gerenciamento de Placas de Video...");
        itemSubMnAbreCadPlacaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSubMnAbreCadPlacaVActionPerformed(evt);
            }
        });
        subMenuCadProd.add(itemSubMnAbreCadPlacaV);

        itemSubMnAbreCadPlacaM.setText("Abir Gerenciamento de Placas Mães...");
        itemSubMnAbreCadPlacaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSubMnAbreCadPlacaMActionPerformed(evt);
            }
        });
        subMenuCadProd.add(itemSubMnAbreCadPlacaM);

        mnCadProd.add(subMenuCadProd);

        mnBarPrincipal.add(mnCadProd);

        mnRelProd.setText("Relatórios");

        SubMenuRelProd.setText("Abrir Relatório Dos Produtos...");

        itemSubMnAbreRelGerProc.setText("Relatório Geral Dos Processadores");
        itemSubMnAbreRelGerProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSubMnAbreRelGerProcActionPerformed(evt);
            }
        });
        SubMenuRelProd.add(itemSubMnAbreRelGerProc);

        itemSubMnAbreRelGerPlacaV.setText("Relatório Geral Das PlacasDeVideo");
        itemSubMnAbreRelGerPlacaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSubMnAbreRelGerPlacaVActionPerformed(evt);
            }
        });
        SubMenuRelProd.add(itemSubMnAbreRelGerPlacaV);

        itemSubMnAbreRelGerPlacaM.setText("Relatório Geral Das PlacasMãe");
        itemSubMnAbreRelGerPlacaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSubMnAbreRelGerPlacaMActionPerformed(evt);
            }
        });
        SubMenuRelProd.add(itemSubMnAbreRelGerPlacaM);

        jMenuItem1.setText("Relatório Geral De Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        SubMenuRelProd.add(jMenuItem1);

        mnRelProd.add(SubMenuRelProd);

        mnBarPrincipal.add(mnRelProd);

        mnSair.setText("Fechar");

        iMnSair.setText("Fechar");
        iMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMnSairActionPerformed(evt);
            }
        });
        mnSair.add(iMnSair);

        mnBarPrincipal.add(Box.createHorizontalGlue());

        mnBarPrincipal.add(mnSair);

        setJMenuBar(mnBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(rtTitulo)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(rtTitulo)
                .addGap(29, 29, 29)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSubMnAbreCadProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubMnAbreCadProcActionPerformed
       FormCadProc.getCadProc().setVisible(true);
    }//GEN-LAST:event_itemSubMnAbreCadProcActionPerformed

    private void iMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMnSairActionPerformed
        sair();
    }//GEN-LAST:event_iMnSairActionPerformed

    private void itemSubMnAbreRelGerProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubMnAbreRelGerProcActionPerformed
        FormRelGerProc.geraFormRelGerProc().setVisible(true);
    }//GEN-LAST:event_itemSubMnAbreRelGerProcActionPerformed

    private void itemSubMnAbreCadPlacaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubMnAbreCadPlacaVActionPerformed
        FormCadPlacaV.getCadPlacaV().setVisible(true);
    }//GEN-LAST:event_itemSubMnAbreCadPlacaVActionPerformed

    private void itemSubMnAbreRelGerPlacaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubMnAbreRelGerPlacaVActionPerformed
        FormRelGerPlacaV.geraFormRelGerPlacaV().setVisible(true);
    }//GEN-LAST:event_itemSubMnAbreRelGerPlacaVActionPerformed

    private void itemSubMnAbreCadPlacaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubMnAbreCadPlacaMActionPerformed
        FormCadPlacaM.getCadPlacaM().setVisible(true);
    }//GEN-LAST:event_itemSubMnAbreCadPlacaMActionPerformed

    private void itemSubMnAbreRelGerPlacaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSubMnAbreRelGerPlacaMActionPerformed
        FormRelGerPlacaM.geraFormRelGerPlacaM().setVisible(true);
    }//GEN-LAST:event_itemSubMnAbreRelGerPlacaMActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormGerenciaAll.getCerenciaAll().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair da Aplicação?","Saindo",JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SubMenuRelProd;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem iMnSair;
    private javax.swing.JMenuItem itemSubMnAbreCadPlacaM;
    private javax.swing.JMenuItem itemSubMnAbreCadPlacaV;
    private javax.swing.JMenuItem itemSubMnAbreCadProc;
    private javax.swing.JMenuItem itemSubMnAbreRelGerPlacaM;
    private javax.swing.JMenuItem itemSubMnAbreRelGerPlacaV;
    private javax.swing.JMenuItem itemSubMnAbreRelGerProc;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mnBarPrincipal;
    private javax.swing.JMenu mnCadProd;
    private javax.swing.JMenu mnRelProd;
    private javax.swing.JMenu mnSair;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JMenu subMenuCadProd;
    // End of variables declaration//GEN-END:variables
}
